version: '3'
services:
  postgres:
    restart: always
    image: postgres:10-alpine
    environment:
      - POSTGRES_USER=${THICC_USER}
      - POSTGRES_PASSWORD=${THICC_PASSWORD}
      - POSTGRES_DB=${THICC_DB}
    # volumes:
    #   - ./postgres-data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  flask:
    build: ./backend
    environment:
      - DB_USER=${THICC_USER}
      - DB_PASS=${THICC_PASSWORD}
      - DB_NAME=${THICC_DB}
      - FLASK_APP=src
      - FLASK_ENV=development
    ports:
      # - "8000:8000"
      - "5000:5000"
    volumes:
      - ./backend:/thiccflask:rw
    depends_on:
      - postgres
    command: sh -c "dockerize -wait tcp://postgres:5432 && flask run --host=0.0.0.0"
  bot:
      build: ./bot
      tty: true
      image: thiccbot
      environment:
      - DISCORD_ID=${DISCORD_ID}
      - BACKEND_URL=http://flask:5000
      volumes:
      - ./bot:/thiccbot:rw
      depends_on:
      - flask
      command: python thiccBot/main.py
