version: '3'
volumes:
  node_modules:

services:
  postgres:
    restart: always
    image: postgres:10-alpine
    environment:
      - POSTGRES_USER=${THICC_USER}
      - POSTGRES_PASSWORD=${THICC_PASSWORD}
      - POSTGRES_DB=${THICC_DB}
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data:rw
  flask:
    build: ./backend
    tty: true
    environment:
      - DB_USER=${THICC_USER}
      - DB_PASS=${THICC_PASSWORD}
      - DB_NAME=${THICC_DB}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - BOT_API_TOKEN=${BOT_API_TOKEN}
      - SECRET_KEY=${FLASK_SECRET_KEY}
      - LAST_FM_API_KEY=${LAST_FM_API_KEY}
      - LAST_FM_SECRET=${LAST_FM_SECRET}
      - FLASK_APP=src
      - FLASK_ENV=production
    depends_on:
      - postgres
    # run this command when you change db models, this does not detect all changes https://flask-migrate.readthedocs.io/en/latest/ 
    # command: sh -c "dockerize -wait tcp://postgres:5432 && flask db migrate"
    command: sh -c "dockerize -wait tcp://postgres:5432 && flask db upgrade && gunicorn -w 4 -b 0.0.0.0:8000 src:app" #&& flask db upgrade
    # command: sh -c "ls "
  bot:
      build: ./bot
      tty: true
      image: thiccbot
      environment:
      - DISCORD_ID=${DISCORD_ID}
      - BACKEND_URL=http://ngix/api
      - BOT_API_TOKEN=${BOT_API_TOKEN}
      - BOT_ADMIN=${BOT_ADMIN}
      - BOT_ENV=production
      volumes:
      - ./bot:/thiccbot:rw
      depends_on:
      - flask
      command: python thiccBot/main.py
  ngix:
    build: ./prod
    depends_on:
      - flask
    ports:
      - "80:80"
  # web: 
  #   build: ./web
  #   tty: true
  #   environment:
  #     - PORT=4000
  #   ports: 
  #     - "4000:4000"
  #   volumes:
  #     - ./web:/thiccweb:rw
  #     # - node_modules:/thiccweb/node_modules:rw
  #   command: bash -c "cd /thiccweb; rm -f .bsb.lock; npm run dev"
  #   # depends_on:
  #   #   - flask
