version: '3'

services:
  postgres:
    image: postgres:10-alpine
    environment:
      - POSTGRES_USER=thicc
      - POSTGRES_PASSWORD=thicc
      - POSTGRES_DB=thicc
  flask:
    build: ./backend
    image: jrmurray/thiccbot-flask:latest
    depends_on:
      - postgres
  bot:
      build: ./bot
      image: jrmurray/thiccbot-bot:latest
  nginx:
    build: ./prod
    image: jrmurray/thiccbot-nginx:latest
    depends_on:
      - flask
    ports:
      - "80:80"
