[workspace]
members = [
  "crates/*",
]

[package]
name = "thicc_bot"
version = "0.1.0"
edition = "2021"


[dependencies]
bot = { path = "crates/bot" }
tokio = { version = "1.13.0", features = ["full"] }
log = "0.4.0"
env_logger = "0.8.4"
