FROM rust:1.59 as builder

WORKDIR /thiccbot
COPY . .
RUN cargo install --path .
RUN ls
CMD ["thiccbot"]



# FROM debian:buster-slim
# RUN apt-get update && apt-get install -y extra-runtime-dependencies && rm -rf /var/lib/apt/lists/*
# COPY --from=builder /usr/local/cargo/bin/myapp /usr/local/bin/myapp
# CMD ["myapp"]