// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var $$String = require("bs-platform/lib/js/string.js");
var Caml_string = require("bs-platform/lib/js/caml_string.js");

var basePath = "http://localhost:4000";

function join_route(route) {
  var match = Caml_string.get(route, 0);
  if (match !== 47) {
    return $$String.concat("/", /* :: */[
                basePath,
                /* :: */[
                  route,
                  /* [] */0
                ]
              ]);
  } else {
    return basePath + route;
  }
}

function getJson(route, decoder) {
  return fetch(join_route(route)).then((function (prim) {
                  return prim.json();
                })).then((function (json) {
                return Promise.resolve(Curry._1(decoder, json));
              }));
}

exports.basePath = basePath;
exports.join_route = join_route;
exports.getJson = getJson;
/* No side effect */
