"""empty message

Revision ID: 71b60d7ec59c
Revises: d1262eb23fd2
Create Date: 2019-02-28 03:29:50.768010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "71b60d7ec59c"
down_revision = "d1262eb23fd2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "counter",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("server_group_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("count", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["server_group_id"], ["servergroup.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("counter")
    # ### end Alembic commands ###
