"""empty message

Revision ID: d1262eb23fd2
Revises: 
Create Date: 2019-02-28 03:25:53.757096

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd1262eb23fd2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servergroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('album',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_group_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['server_group_id'], ['servergroup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('command', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['server_group_id'], ['servergroup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discordserver',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('server_group_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('command_prefixes', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('message_prefixes', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('admin_role', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['server_group_id'], ['servergroup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('match_case', sa.Boolean(), nullable=True),
    sa.Column('responses', postgresql.ARRAY(sa.String()), nullable=True),
    sa.ForeignKeyConstraint(['server_group_id'], ['servergroup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_group_id', sa.Integer(), nullable=False),
    sa.Column('quote_str', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['server_group_id'], ['servergroup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('albumentry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('albumentry')
    op.drop_table('quotes')
    op.drop_table('keywords')
    op.drop_table('discordserver')
    op.drop_table('alias')
    op.drop_table('album')
    op.drop_table('servergroup')
    # ### end Alembic commands ###
