"""empty message

Revision ID: f753a6101f34
Revises: 9e2734465d2b
Create Date: 2018-12-30 23:08:56.012169

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f753a6101f34'
down_revision = '9e2734465d2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discordserver', sa.Column('admin_roles', sa.BIGINT(), nullable=True))
    # op.alter_column('discordserver', 'command_prefix',
    #            existing_type=sa.VARCHAR(),
    #            type_=postgresql.ARRAY(sa.String()),
    #            existing_nullable=True)
    # ### end Alembic commands ###
    op.drop_column('discordserver', 'command_prefix')
    op.add_column('discordserver', sa.Column('command_prefix',
                postgresql.ARRAY(sa.String()), nullable=True))



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('discordserver', 'command_prefix',
    #            existing_type=postgresql.ARRAY(sa.String()),
    #            type_=sa.VARCHAR(),
    #            existing_nullable=True)
    op.drop_column('discordserver', 'admin_roles')
    # ### end Alembic commands ###
    op.drop_column('discordserver', 'command_prefix')
    op.add_column('discordserver', sa.Column('admin_roles', sa.VARCHAR(), nullable=True))


