"""empty message

Revision ID: f95f9afb411a
Revises: 6283181ce91a
Create Date: 2020-06-14 23:19:34.666804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f95f9afb411a'
down_revision = '6283181ce91a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discord_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_id', sa.BIGINT(), nullable=False),
    sa.Column('role_id', sa.BIGINT(), nullable=True),
    sa.Column('message_id', sa.BIGINT(), nullable=True),
    sa.Column('channel_id', sa.BIGINT(), nullable=True),
    sa.ForeignKeyConstraint(['discord_id'], ['discordserver.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discord_role')
    # ### end Alembic commands ###
