// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function getJson(route, decoder, param) {
  return fetch(route).then((function (prim) {
                  return prim.json();
                })).then((function (json) {
                return Promise.resolve(Curry._1(decoder, json));
              }));
}

exports.getJson = getJson;
/* No side effect */
