/* 
 * API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct AlbumEntry {
  #[serde(rename = "id")]
  id: Option<i32>,
  #[serde(rename = "link")]
  link: Option<String>
}

impl AlbumEntry {
  pub fn new() -> AlbumEntry {
    AlbumEntry {
      id: None,
      link: None
    }
  }

  pub fn set_id(&mut self, id: i32) {
    self.id = Some(id);
  }

  pub fn with_id(mut self, id: i32) -> AlbumEntry {
    self.id = Some(id);
    self
  }

  pub fn id(&self) -> Option<&i32> {
    self.id.as_ref()
  }

  pub fn reset_id(&mut self) {
    self.id = None;
  }

  pub fn set_link(&mut self, link: String) {
    self.link = Some(link);
  }

  pub fn with_link(mut self, link: String) -> AlbumEntry {
    self.link = Some(link);
    self
  }

  pub fn link(&self) -> Option<&String> {
    self.link.as_ref()
  }

  pub fn reset_link(&mut self) {
    self.link = None;
  }

}



