/* 
 * API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Alias {
  #[serde(rename = "name")]
  name: Option<String>,
  #[serde(rename = "command")]
  command: Option<String>
}

impl Alias {
  pub fn new() -> Alias {
    Alias {
      name: None,
      command: None
    }
  }

  pub fn set_name(&mut self, name: String) {
    self.name = Some(name);
  }

  pub fn with_name(mut self, name: String) -> Alias {
    self.name = Some(name);
    self
  }

  pub fn name(&self) -> Option<&String> {
    self.name.as_ref()
  }

  pub fn reset_name(&mut self) {
    self.name = None;
  }

  pub fn set_command(&mut self, command: String) {
    self.command = Some(command);
  }

  pub fn with_command(mut self, command: String) -> Alias {
    self.command = Some(command);
    self
  }

  pub fn command(&self) -> Option<&String> {
    self.command.as_ref()
  }

  pub fn reset_command(&mut self) {
    self.command = None;
  }

}



