command_prefix: "?" # this is the deafult prefix to be used, wont be used if prefixes are set in a server
initial_extensions:
    - 'cogs.alias'
    - 'cogs.basics'
    - 'cogs.admin'
    - 'cogs.botAdmin'
    - 'cogs.keyWords'
    - 'cogs.quotes'
    - 'cogs.album'
    - 'cogs.counter'