command_prefix: "?" # this is the deafult prefix to be used, can be changed per server
bot_admin: 83736990750605312 #set this to your discord ID
initial_extensions:
    - 'cogs.alias'
    - 'cogs.basics'
    - 'cogs.BotAdmin'