command_prefix: "?" # this is the deafult prefix to be used, can be changed per server
initial_extensions:
    - 'cogs.alias'
    - 'cogs.basics'
    - 'cogs.admin'
    - 'cogs.botAdmin'
    - 'cogs.keyWords'
    - 'cogs.quotes'
    - 'cogs.album'