name: Build and push images

on: push

jobs:
  build-flask:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build API image
        run: docker-compose -f docker-compose.ci.yml build flask
      - name: Push flask image
        if: github.ref == 'refs/heads/master'
        run: |
          docker login -u ${{ secrets.dockerHubUserName }} -p ${{ secrets.dockerHubToken }}
          docker-compose -f docker-compose.ci.yml push flask
  build-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build & push bot image
        if: github.ref == 'refs/heads/master'
        run: |
          docker login -u ${{ secrets.dockerHubUserName }} -p ${{ secrets.dockerHubToken }}
          docker-compose -f docker-compose.ci.yml build bot
          docker-compose -f docker-compose.ci.yml push bot
  build-nginx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build & push nginx image
        if: github.ref == 'refs/heads/master'
        run: |
          docker login -u ${{ secrets.dockerHubUserName }} -p ${{ secrets.dockerHubToken }}
          docker-compose -f docker-compose.ci.yml build nginx
          docker-compose -f docker-compose.ci.yml push nginx
